import React, { useEffect, useState } from 'react';
import Card from '../components/Card';
import Badge from '../components/Badge';
import { apiService } from '../services/api';
import { useNavigate } from 'react-router-dom';

const InsightsList = () => {
  const [insights, setInsights] = useState([]);
  const navigate = useNavigate();

  useEffect(() => {
    const fetchInsights = async () => {
      try {
        const data = await apiService.getInsights(1);
        setInsights(data || []);
      } catch (e) {
        console.error(e);
      }
    };
    fetchInsights();
  }, []);

  return (
    <div>
      <div className="page-header">
        <h1 className="page-title">AI Insights</h1>
        <p className="page-subtitle">Your personalized financial advice generated by the Hybrid Agent.</p>
      </div>

      <div className="grid-3">
        {insights.length > 0 ? insights.slice().reverse().map(insight => (
          <Card 
            key={insight.id} 
            glow={insight.anomalyType === 'VELOCITY' ? 'red' : insight.source === 'AI_GENERATED' ? 'purple' : ''}
            onClick={() => navigate(`/insights/${insight.id}`)}
          >
            <div style={{ marginBottom: '16px', display: 'flex', gap: '8px', flexWrap: 'wrap' }}>
              <Badge type={insight.source}>{insight.source.replace('_', ' ')}</Badge>
              {insight.anomalyType !== 'NONE' && <Badge type={insight.anomalyType}>{insight.anomalyType}</Badge>}
            </div>
            <p style={{ fontSize: '15px', marginBottom: '16px', color: 'var(--text-primary)' }}>
              {insight.insightText}
            </p>
            <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12px', color: 'var(--text-secondary)' }}>
              <span>{insight.createdAt ? insight.createdAt.split('T')[0] : 'Today'}</span>
              <span>Click for details &rarr;</span>
            </div>
          </Card>
        )) : (
          <div style={{ color: 'var(--text-secondary)' }}>No insights generated yet. Add a transaction!</div>
        )}
      </div>
    </div>
  );
};

export default InsightsList;
